// @ts-nocheck
async function createLuauModule(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.WorkerGlobalScope,ba="./this.program",ca=import.meta.url,m="",da,n;if(globalThis.window||aa){try{m=(new URL(".",ca)).href}catch{}aa&&(n=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}
var ea=console.log.bind(console),p=console.error.bind(console),q,v=!1,x,fa,ha,z,B,C,E,F,G,H,I,ia=!1;function la(){var a=J.buffer;z=new Int8Array(a);C=new Int16Array(a);B=new Uint8Array(a);new Uint16Array(a);E=new Int32Array(a);F=new Uint32Array(a);G=new Float32Array(a);H=new Float64Array(a);I=new BigInt64Array(a);new BigUint64Array(a)}function K(a){h.onAbort?.(a);a="Aborted("+a+")";p(a);v=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ha?.(a);throw a;}var M;
async function ma(a){if(!q)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==M&&q)a=new Uint8Array(q);else if(n)a=n(a);else throw"both async and sync fetching of the wasm failed";return a}async function na(a,b){try{var c=await ma(a);return await WebAssembly.instantiate(c,b)}catch(d){p(`failed to asynchronously prepare wasm: ${d}`),K(d)}}
async function oa(a){var b=M;if(!q)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){p(`wasm streaming compile failed: ${d}`),p("falling back to ArrayBuffer instantiation")}return na(b,a)}class pa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var qa=a=>{for(;0<a.length;)a.shift()(h)},ra=[],sa=[],ta=()=>{var a=h.preRun.shift();sa.push(a)},N=!0,O=[],P=0,Q=0;
class R{constructor(a){this.Ta=a;this.Sa=a-24}}
var va=a=>{var b=Q;if(!b)return S(0),0;var c=new R(b);F[c.Sa+16>>2]=b;var d=F[c.Sa+4>>2];if(!d)return S(0),b;for(var e of a){if(0===e||e===d)break;if(ua(e,d,c.Sa+16))return S(e),b}S(d);return b},xa=()=>{var a=O.pop();a||K("no exception to throw");var b=a.Ta;0==z[a.Sa+13]&&(O.push(a),z[a.Sa+13]=1,z[a.Sa+12]=0,P++);wa(b);Q=b;throw Q;},ya=0,za=[0,31,60,91,121,152,182,213,244,274,305,335],Aa=[0,31,59,90,120,151,181,212,243,273,304,334],Ba=globalThis.TextDecoder&&new TextDecoder,Ca=(a,b=0,c,d)=>{var e=
b;c=e+c;if(d)d=c;else{for(;a[e]&&!(e>=c);)++e;d=e}if(16<d-b&&a.buffer&&Ba)return Ba.decode(a.subarray(b,d));for(e="";b<d;)if(c=a[b++],c&128){var f=a[b++]&63;if(192==(c&224))e+=String.fromCharCode((c&31)<<6|f);else{var g=a[b++]&63;c=224==(c&240)?(c&15)<<12|f<<6|g:(c&7)<<18|f<<12|g<<6|a[b++]&63;65536>c?e+=String.fromCharCode(c):(c-=65536,e+=String.fromCharCode(55296|c>>10,56320|c&1023))}}else e+=String.fromCharCode(c);return e},T={},Da=a=>{if(!(a instanceof pa||"unwind"==a))throw a;},Ea=a=>{x=a;N||
0<ya||(h.onExit?.(a),v=!0);throw new pa(a);},Fa=a=>{if(!v)try{a()}catch(b){Da(b)}finally{if(!(N||0<ya))try{x=a=x,Ea(a)}catch(b){Da(b)}}},U=(a,b,c)=>{var d=B;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=128|g>>6&
63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},Ga={},Ia=()=>{if(!Ha){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Ga)void 0===Ga[b]?delete a[b]:a[b]=Ga[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ha=c}return Ha},Ha,Ja=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ka=[null,[],[]],La=
[],V=a=>{var b=La[a];b||(La[a]=b=Ma.get(a));return b},Oa=(a,b,c,d)=>{var e={string:l=>{var t=0;if(null!==l&&void 0!==l&&0!==l){t=Ja(l)+1;var u=Na(t);U(l,u,t);t=u}return t},array:l=>{var t=Na(l.length);z.set(l,t);return t}};a=h["_"+a];var f=[],g=0;if(d)for(var k=0;k<d.length;k++){var r=e[c[k]];r?(0===g&&(g=W()),f[k]=r(d[k])):f[k]=d[k]}c=a(...f);return c=function(l){0!==g&&X(g);return"string"===b?l?Ca(B,l):"":"boolean"===b?!!l:l}(c)};h.noExitRuntime&&(N=h.noExitRuntime);h.print&&(ea=h.print);
h.printErr&&(p=h.printErr);h.wasmBinary&&(q=h.wasmBinary);h.thisProgram&&(ba=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.ccall=Oa;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>Oa(a,b,c,f,d)};
h.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":z[a]=b;break;case "i8":z[a]=b;break;case "i16":C[a>>1]=b;break;case "i32":E[a>>2]=b;break;case "i64":I[a>>3]=BigInt(b);break;case "float":G[a>>2]=b;break;case "double":H[a>>3]=b;break;case "*":F[a>>2]=b;break;default:K(`invalid type for setValue: ${c}`)}};
h.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return z[a];case "i8":return z[a];case "i16":return C[a>>1];case "i32":return E[a>>2];case "i64":return I[a>>3];case "float":return G[a>>2];case "double":return H[a>>3];case "*":return F[a>>2];default:K(`invalid type for getValue: ${b}`)}};h.UTF8ToString=(a,b,c)=>a?Ca(B,a,b,c):"";h.stringToUTF8=(a,b,c)=>U(a,b,c);h.lengthBytesUTF8=Ja;
var Pa,Y,S,X,Na,W,Qa,wa,ua,Ra,J,Ma,Jb={u:a=>{var b=new R(a);0==z[b.Sa+12]&&(z[b.Sa+12]=1,P--);z[b.Sa+13]=0;O.push(b);return Ra(a)},B:()=>{Y(0,0);var a=O.pop();Qa(a.Ta);Q=0},a:()=>va([]),k:a=>va([a]),x:(a,b)=>va([a,b]),Q:xa,Z:a=>{a&&(a=new R(a),O.push(a),z[a.Sa+13]=1,xa())},s:(a,b,c)=>{var d=new R(a);F[d.Sa+16>>2]=0;F[d.Sa+4>>2]=b;F[d.Sa+8>>2]=c;wa(a);Q=a;P++;throw Q;},_:()=>P,d:a=>{Q||=a;throw Q;},W:()=>K(""),U:()=>{N=!1;ya=0},da:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);
a=new Date(1E3*a);E[b>>2]=a.getUTCSeconds();E[b+4>>2]=a.getUTCMinutes();E[b+8>>2]=a.getUTCHours();E[b+12>>2]=a.getUTCDate();E[b+16>>2]=a.getUTCMonth();E[b+20>>2]=a.getUTCFullYear()-1900;E[b+24>>2]=a.getUTCDay();E[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},ea:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>
2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();var c=a.getFullYear();E[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Aa:za)[a.getMonth()]+a.getDate()-1|0;E[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();E[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},ca:function(){},V:(a,b)=>{T[a]&&(clearTimeout(T[a].id),delete T[a]);if(!b)return 0;var c=setTimeout(()=>{delete T[a];Fa(()=>Pa(a,performance.now()))},
b);T[a]={id:c,Ua:b};return 0},fa:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();F[a>>2]=60*Math.max(f,e);E[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(U(a,c,17),U(b,d,17)):(U(a,d,17),U(b,c,17))},ha:function(a,b,c){if(!(0<=a&&3>=a))return 28;I[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));
return 0},ga:()=>Date.now(),aa:()=>536870912,$:a=>{var b=B.length;a>>>=0;if(536870912<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(536870912,65536*Math.ceil(Math.max(a,d)/65536))-J.buffer.byteLength+65535)/65536|0;try{J.grow(d);la();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},X:(a,b)=>{var c=0,d=0,e;for(e of Ia()){var f=b+c;F[a+d>>2]=f;c+=U(e,f,Infinity)+1;d+=4}return 0},Y:(a,b)=>{var c=Ia();F[a>>2]=c.length;a=0;for(var d of c)a+=Ja(d)+
1;F[b>>2]=a;return 0},ba:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=F[b>>2],k=F[b+4>>2];b+=8;for(var r=0;r<k;r++){var l=a,t=B[g+r],u=Ka[l];0===t||10===t?((1===l?ea:p)(Ca(u)),u.length=0):u.push(t)}e+=k}F[d>>2]=e;return 0},I:Sa,L:Ta,A:Ua,f:Va,H:Wa,c:Xa,h:Ya,n:Za,o:$a,p:ab,y:bb,r:cb,ma:db,G:eb,la:fb,na:gb,J:hb,O:ib,R:jb,S:kb,ka:lb,j:mb,b:nb,ja:ob,e:pb,D:qb,N:rb,M:sb,g:tb,i:ub,m:vb,l:wb,q:xb,t:yb,w:zb,z:Ab,E:Bb,F:Cb,oa:Db,C:Eb,K:Fb,ia:Gb,P:Hb,pa:Ib,v:a=>a,T:Ea};
function pb(a,b,c){var d=W();try{V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Xa(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function Ya(a,b,c,d){var e=W();try{return V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function wb(a,b,c,d,e,f,g){var k=W();try{V(a)(b,c,d,e,f,g)}catch(r){X(k);if(r!==r+0)throw r;Y(1,0)}}function tb(a,b,c,d){var e=W();try{V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}
function nb(a,b){var c=W();try{V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function vb(a,b,c,d,e,f){var g=W();try{V(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Y(1,0)}}function Va(a,b){var c=W();try{return V(a)(b)}catch(d){X(c);if(d!==d+0)throw d;Y(1,0)}}function Za(a,b,c,d,e){var f=W();try{return V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}function $a(a,b,c,d,e,f){var g=W();try{return V(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Y(1,0)}}
function mb(a){var b=W();try{V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}function ub(a,b,c,d,e){var f=W();try{V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}function Ta(a,b,c,d){var e=W();try{return V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function Ib(a,b,c){var d=W();try{V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function ab(a,b,c,d,e,f,g){var k=W();try{return V(a)(b,c,d,e,f,g)}catch(r){X(k);if(r!==r+0)throw r;Y(1,0)}}
function Bb(a,b,c,d,e,f,g,k,r,l,t,u){var w=W();try{V(a)(b,c,d,e,f,g,k,r,l,t,u)}catch(y){X(w);if(y!==y+0)throw y;Y(1,0)}}function Ab(a,b,c,d,e,f,g,k,r,l,t){var u=W();try{V(a)(b,c,d,e,f,g,k,r,l,t)}catch(w){X(u);if(w!==w+0)throw w;Y(1,0)}}function Eb(a,b,c,d,e,f){var g=W();try{V(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Y(1,0)}}function Fb(a,b,c,d,e){var f=W();try{V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}
function bb(a,b,c,d,e,f,g,k){var r=W();try{return V(a)(b,c,d,e,f,g,k)}catch(l){X(r);if(l!==l+0)throw l;Y(1,0)}}function xb(a,b,c,d,e,f,g,k){var r=W();try{V(a)(b,c,d,e,f,g,k)}catch(l){X(r);if(l!==l+0)throw l;Y(1,0)}}function hb(a,b,c,d,e,f,g){var k=W();try{return V(a)(b,c,d,e,f,g)}catch(r){X(k);if(r!==r+0)throw r;Y(1,0)}}function cb(a,b,c,d,e,f,g,k,r){var l=W();try{return V(a)(b,c,d,e,f,g,k,r)}catch(t){X(l);if(t!==t+0)throw t;Y(1,0)}}
function yb(a,b,c,d,e,f,g,k,r){var l=W();try{V(a)(b,c,d,e,f,g,k,r)}catch(t){X(l);if(t!==t+0)throw t;Y(1,0)}}function Ua(a){var b=W();try{return V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}function zb(a,b,c,d,e,f,g,k,r,l){var t=W();try{V(a)(b,c,d,e,f,g,k,r,l)}catch(u){X(t);if(u!==u+0)throw u;Y(1,0)}}function Db(a,b,c,d,e,f,g,k,r,l,t,u,w,y,A,D,ja){var L=W();try{V(a)(b,c,d,e,f,g,k,r,l,t,u,w,y,A,D,ja)}catch(ka){X(L);if(ka!==ka+0)throw ka;Y(1,0)}}
function Sa(a){var b=W();try{return V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0)}}function gb(a,b,c,d,e,f,g,k,r,l,t,u,w,y){var A=W();try{return V(a)(b,c,d,e,f,g,k,r,l,t,u,w,y)}catch(D){X(A);if(D!==D+0)throw D;Y(1,0)}}function db(a,b,c,d,e,f,g,k,r,l,t){var u=W();try{return V(a)(b,c,d,e,f,g,k,r,l,t)}catch(w){X(u);if(w!==w+0)throw w;Y(1,0)}}function fb(a,b,c,d,e,f,g,k,r,l,t,u,w){var y=W();try{return V(a)(b,c,d,e,f,g,k,r,l,t,u,w)}catch(A){X(y);if(A!==A+0)throw A;Y(1,0)}}
function Hb(a,b,c,d,e){var f=W();try{V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}function ib(a,b,c,d){var e=W();try{return V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function lb(a,b,c,d,e,f){var g=W();try{return V(a)(b,c,d,e,f)}catch(k){X(g);if(k!==k+0)throw k;Y(1,0);return 0n}}function Wa(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function ob(a,b,c){var d=W();try{V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}
function qb(a,b,c,d){var e=W();try{V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function rb(a,b,c,d,e){var f=W();try{V(a)(b,c,d,e)}catch(g){X(f);if(g!==g+0)throw g;Y(1,0)}}function Gb(a,b,c,d){var e=W();try{V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function sb(a,b,c,d){var e=W();try{V(a)(b,c,d)}catch(f){X(e);if(f!==f+0)throw f;Y(1,0)}}function kb(a){var b=W();try{return V(a)()}catch(c){X(b);if(c!==c+0)throw c;Y(1,0);return 0n}}
function jb(a,b,c){var d=W();try{return V(a)(b,c)}catch(e){X(d);if(e!==e+0)throw e;Y(1,0)}}function eb(a,b,c,d,e,f,g,k,r,l,t,u){var w=W();try{return V(a)(b,c,d,e,f,g,k,r,l,t,u)}catch(y){X(w);if(y!==y+0)throw y;Y(1,0)}}function Cb(a,b,c,d,e,f,g,k,r,l,t,u,w,y,A,D){var ja=W();try{V(a)(b,c,d,e,f,g,k,r,l,t,u,w,y,A,D)}catch(L){X(ja);if(L!==L+0)throw L;Y(1,0)}}var Z;
Z=await (async function(){function a(c){c=Z=c.exports;h._luau_add_module=c.sa;h._luau_clear_modules=c.ta;h._luau_get_modules=c.ua;h._luau_execute=c.va;h._free=c.wa;h._luau_dump_bytecode=c.ya;h._luau_set_mode=c.za;h._luau_set_solver=c.Aa;h._luau_set_source=c.Ba;h._luau_clear_sources=c.Ca;h._luau_get_diagnostics=c.Da;h._luau_autocomplete=c.Ea;h._luau_hover=c.Fa;h._luau_signature_help=c.Ga;h._malloc=c.Ha;Pa=c.Ia;Y=c.Ja;S=c.Ka;X=c.La;Na=c.Ma;W=c.Na;Qa=c.Oa;wa=c.Pa;ua=c.Qa;Ra=c.Ra;J=c.qa;Ma=
c.xa;la();return Z}var b={a:Jb};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});M??=h.locateFile?h.locateFile?h.locateFile("luau.wasm",m):m+"luau.wasm":(new URL(/* @vite-ignore */ "luau.wasm",import.meta.url)).href;return a((await oa(b)).instance)}());
(function(){function a(){h.calledRun=!0;if(!v){ia=!0;Z.ra();fa?.(h);h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();ra.push(b)}qa(ra)}}if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ta();qa(sa);h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()})();ia?moduleRtn=h:moduleRtn=new Promise((a,b)=>{fa=a;ha=b});
;return moduleRtn}export default createLuauModule;
